src/objects/Latch_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Latch_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Latch Account</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Latch Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Latch Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Latch_Application__mdt.object
<CustomObject>
    <fields>
        <fullName>Application_Id__c</fullName>
        <label>Application Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Latch Application</label>
    <pluralLabel>Latch Applications</pluralLabel>
</CustomObject>

src/classes/LatchClient.cls
public with sharing class LatchClient {
    final private static String API_URL = '/api/1.1';
    final private static String CHECK_STATUS_URL = '/status/{0}/op/{1}';
    final private static String PAIRING_URL = '/pair/{0}';
    final private static String UNPAIRING_URL = '/unpair/{0}';
	final private LatchConnection lc;
   	
    private String accId;
    private Boolean userPaired = false;
    
    public LatchClient(String latchApplicationName) {
        List<Latch_Account__c> accts = [SELECT Account_Id__c FROM Latch_Account__c WHERE User__c = :UserInfo.getUserId()];
        if (!accts.isEmpty()) {
            this.accId = accts.get(0).Account_Id__c;
            this.userPaired = true;
        }
        this.lc = createConnection(latchApplicationName);
    }
    
    public LatchClient(String latchApplicationName, String accId) {
        this.accId = accId;
        this.userPaired = true;
        this.lc = createConnection(latchApplicationName);
    }
    
    public Boolean isLatchOpen(String opId) {
        if (userPaired) {
            String url = String.format(API_URL + CHECK_STATUS_URL, new String[] {
                accId, opId
            });
            
            return parseLatchStatus(lc.get(url), opId);
        } else {
            System.debug('The user is not paired with latch, returning latch as opened');
            return true;
        }
    }
    
    public void unpair(String accountId) {
        if (userPaired) {
        	String jsonLatchResponse = lc.get(String.format(API_URL + UNPAIRING_URL, new String[] {accountId}));
            if (isUnpairingSuccessful(jsonLatchResponse)) {
            	userPaired = false;
                removeLatchAccount(accountId);
            }
        } else {
            System.debug(UserInfo.getName() + ' was not paired');
        }
        
    }
    
    public String pair(String pairingToken) {
        return pair(pairingToken, false);
    }
    
    public String pair(String pairingToken, Boolean force) {
        if (userPaired && !force) {
            System.debug('User already paired with latch');
            return accId;
        }
        
        String jsonLatchResponse = lc.get(String.format(API_URL + PAIRING_URL, new String[] {pairingToken}));
        
        String newAccId = parseAccountFromPair(jsonLatchResponse);
        if (newAccId != null) {
            accId = newAccId;
            userPaired = true;
            
            addLatchPairing(newAccId);
        }
        
        return newAccId;
    }
    
    private void addLatchPairing(String accId) {
        Latch_Account__c acct = new Latch_Account__c(
        	User__c = UserInfo.getUserId(),
            Account_Id__c = accId
        );
        
        insert acct;
    }
    
    private void removeLatchAccount(String accId) {
        List<Latch_Account__c> las = [
            SELECT Account_Id__c
              FROM Latch_Account__c
             WHERE Account_Id__c = :accId
               AND User__c = :UserInfo.getUserId()
        ];
        
        delete las;
    }
    
    private Boolean isUnpairingSuccessful(String jsonObject) {
        Map<String, Object> latchResponse = (Map<String, Object>) JSON.deserializeUntyped(jsonObject);
        Boolean failed = true;
        
        if (latchResponse.get('error') != null) {
            Map<String, Object> error = (Map<String, Object>) latchResponse.get('error');
            System.debug('Latch Pairing Error: (' 
                         + error.get('code') + ') ' 
                         + error.get('message'));
            failed = false;
        }
        
        return failed;
    }
    
    private String parseAccountFromPair(String jsonObject) {
         Map<String, Object> latchResponse = (Map<String, Object>) JSON.deserializeUntyped(jsonObject);
        
        System.debug('Latch Response: ' + latchResponse);
        
        if (latchResponse.get('data') != null) {
            Map<String, Object> data = (Map<String, Object>) latchResponse.get('data');
        	return (String) data.get('accountId');
        } else if (latchResponse.get('error') != null) {
            Map<String, Object> error = (Map<String, Object>) latchResponse.get('error');
            System.debug('Latch Pairing Error: (' 
                         + error.get('code') + ') ' 
                         + error.get('message'));
        } else {
            System.debug('Cannot parse Latch response while pairing: ' + jsonObject);
        }
        
        return null;
    }
    
    private Boolean parseLatchStatus(String jsonLatchResponse, String opId) {
        Map<String, Object> latchResponse = (Map<String, Object>) JSON.deserializeUntyped(jsonLatchResponse);
        if (latchResponse.get('data') != null) {
            Map<String, Object> data = (Map<String, Object>) latchResponse.get('data');
            Map<String, Object> operations = (Map<String, Object>) data.get('operations');
            Map<String, Object> loginOperation = (Map<String, Object>) operations.get(opId);
            String latchStatus = (String) loginOperation.get('status');
            
            return latchStatus == 'on';
        } else {
            return true;
        }
    }
    
    private LatchConnection createConnection(String latchApplicationName) {
        List<Latch_Application__mdt> las = [
            SELECT Application_Id__c,
             	   Secret__c 
			  FROM Latch_Application__mdt
             WHERE Label = :latchApplicationName];
        
        return new LatchConnection(las.get(0).Application_Id__c, las.get(0).Secret__c);
    }
}