src/objects/Latch_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <label>Account Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Latch_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Latch Account</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Latch Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Latch Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LatchUserManagerController.cls
public with sharing class LatchUserManagerController {
    @AuraEnabled
    public static Latch_Account__c setup() {
        List<Latch_Account__c> las = [
            SELECT Account_Id__c
              FROM Latch_Account__c
             WHERE User__c = :UserInfo.getUserId()
        ];

        return las.isEmpty() ? new Latch_Account__c() : las.get(0);
    }
    
    @AuraEnabled
    public static String pair(String pairingToken) {
        return new LatchClient('Salesforce').pair(pairingToken);
    }
    
    @AuraEnabled
    public static void unpair(String accountId) {
        new LatchClient('Salesforce').unpair(accountId);
    }
}